# Generated by Django 3.1.2 on 2020-10-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GameMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerclass', models.CharField(choices=[('Knight', 'Knight'), ('Wizard', 'Wizard'), ('Thief', 'Thief'), ('Paladin', 'Paladin')], default='Knight', max_length=15, verbose_name='Class')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('level', models.IntegerField(default=0, verbose_name='Player level')),
                ('name', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Player.player', verbose_name='User Name')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GameMap.location')),
            ],
        ),
    ]
