# Generated by Django 3.1.2 on 2020-10-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.itemtype'),
        ),
    ]
