# Generated by Django 3.1.2 on 2020-10-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0002_auto_20201003_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(max_length=1000)),
                ('playerFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerFrom', to='Player.player')),
                ('playerTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerTo', to='Player.player')),
            ],
        ),
    ]
